[package]
name = "opcua-simple-server"
version = "0.12.0" # OPCUARustVersion
authors = ["Adam Lock <locka99@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
log = "0.4"

[dependencies.opcua]
path = "../../lib"
version = "0.12.0" # OPCUARustVersion
features = ["server", "console-logging"]
