[workspace]
members = [
    "types",
    "core",
    "client",
    "server",
    "console-logging",
    "integration",
    "samples/demo-server",
    "samples/simple-client",
    "samples/mqtt-client",
    "samples/gfx-client",
    "samples/simple-server",
    "samples/chess-server",
    "samples/discovery-client",
    "tools/certificate-creator"
]
