[package]
name = "opcua-web-client"
version = "0.9.1" # OPCUARustVersion
authors = ["Adam Lock <locka99@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7"
actix-web = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
pico-args = "0.3"
tokio = { version = "1", features = ["full"] }

[dependencies.opcua-client]
path = "../../client"
version = "0.9.1" # OPCUARustVersion

[dependencies.opcua-console-logging]
path = "../../console-logging"
version = "0.9.1" # OPCUARustVersion
