[package]
name = "opcua-integration"
version = "0.7.0" # OPCUARustVersion
authors = ["Adam Lock <locka99@gmail.com>"]
edition = "2018"

[dev-dependencies]
log = "0.4"
chrono = "0.4"

[dev-dependencies.opcua-server]
path = "../server"
version = "0.7.0" # OPCUARustVersion

[dev-dependencies.opcua-client]
path = "../client"
version = "0.7.0" # OPCUARustVersion

[dev-dependencies.opcua-core]
path = "../core"
version = "0.7.0" # OPCUARustVersion

[dev-dependencies.opcua-console-logging]
path = "../console-logging"
version = "0.7.0" # OPCUARustVersion
